/** Volunteer-facing Hub action labels. Prefer these over technical verbs. */
export const HUB_ACTION_LABELS = {
  previewChanges: "Preview my changes",
  viewFullSizePreview: "View full-size preview",
  makeLive: "Make this live on the website",
  cancelChanges: "Cancel changes",
  changeSection: "Change this section",
  useCurrentText: "Use current text as my starting point",
  useCurrentInformation: "Use current information as my starting point",
  changeBranchDetails: "Change branch details",
  changeFeaturedProgram: "Choose a different featured program",
  makeFeaturedLive: "Make this program live on the homepage",
  changeSermonDetails: "Change these details",
  makeSermonDetailsLive: "Make these sermon details live",
  makeChangesLive: "Make these changes live",
  checkAndPreview: "Check and Preview",
  startLivestream: "Start a Facebook livestream",
  changeLiveVideo: "Change live video",
  updateLiveVideo: "Update the live video",
  makeLivestreamLive: "Make Livestream Live",
  turnOffLivestream: "Turn off the livestream",
  saveDraft: "Save my draft",
  markReadyForPreview: "Mark ready for preview",
  removeFromWebsite: "Remove from public website",
  restoreDraft: "Move back to draft",
  signOut: "Sign out",
  replacePhoto: "Replace Photo",
  addPhotoToBranch: "Add this photo to the branch",
  preparePhoto: "Check how the photo will look",
  saveBranch: "Make these branch details live",
  saveSermonDraft: "Save my sermon draft",
  createProgramDraft: "Save as a draft (not public yet)",
  createSermonDraft: "Save as a draft (not public yet)",
  replayTour: "Replay Hub Tour",
  helpTutorial: "Help & Tutorial",
  skipTour: "Skip tour",
  nextTour: "Next",
  backTour: "Back",
  finishTour: "Finish tour",
  startTour: "Show me around",
} as const;

export const HUB_STATUS_LABELS: Record<string, string> = {
  published: "Live on website",
  archived: "Removed from public website",
  draft: "Draft — not on the website",
  preview: "Ready to preview",
};
