/**
 * Central machine-readable QA manifest — known KCMI application surface.
 */

import type { QaRouteEntry, QaStateEntry } from "./types";
import { STAGING_QA_PROGRAM_ID } from "./mutation-policy";

export const QA_MANIFEST_VERSION = "QA1-2026-09-12";

export const PUBLIC_ROUTES: QaRouteEntry[] = [
  {
    path: "/",
    surface: "PUBLIC",
    landmark: /raising kings|kcmi/i,
    auth: "none",
    keyControls: ["main nav", "Spotlight", "mobile menu"],
    viewports: ["390", "768", "1280", "1920"],
    mutationRisk: "SAFE",
    workflows: ["public-navigation"],
    a11yScan: true,
    visualEligible: true,
  },
  {
    path: "/about",
    surface: "PUBLIC",
    landmark: /about/i,
    auth: "none",
    viewports: ["390", "1280"],
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: true,
  },
  {
    path: "/about/apostle-frank-aikins",
    surface: "PUBLIC",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
  },
  {
    path: "/locations",
    surface: "PUBLIC",
    landmark: /location/i,
    auth: "none",
    keyControls: ["search", "country filter"],
    viewports: ["390", "768", "1280"],
    mutationRisk: "LOCAL_STATE",
    workflows: ["location-finder"],
    a11yScan: true,
    visualEligible: true,
  },
  {
    path: "/locations/headquarters",
    surface: "PUBLIC",
    auth: "none",
    mutationRisk: "SAFE",
    workflows: ["location-finder"],
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/services",
    surface: "PUBLIC",
    landmark: /service/i,
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/sermons",
    surface: "PUBLIC",
    landmark: /sermon/i,
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/contact",
    surface: "PUBLIC",
    landmark: /contact/i,
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/giving",
    surface: "PUBLIC",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: false,
    notes: "Giving UX exists; D2 rebuild not started",
  },
  {
    path: "/livestream",
    surface: "PUBLIC",
    landmark: /live/i,
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: true,
  },
  {
    path: "/events",
    surface: "PUBLIC",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
    notes: "Legacy/listing surface; full Events/Camp not in scope",
  },
  {
    path: "/faqs",
    surface: "PUBLIC",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
  },
  {
    path: "/privacy",
    surface: "PUBLIC",
    landmark: /privacy/i,
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/terms",
    surface: "PUBLIC",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
  },
  {
    path: "/mission",
    surface: "PUBLIC",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
  },
];

export const AUTH_ROUTES: QaRouteEntry[] = [
  {
    path: "/auth/sign-in",
    surface: "AUTH",
    landmark: /sign in to the kcmi hub/i,
    auth: "none",
    keyControls: ["email", "password", "sign in"],
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/auth/mfa",
    surface: "AUTH",
    auth: "staff",
    mutationRisk: "SAFE",
    a11yScan: true,
    visualEligible: false,
  },
];

export const HUB_ROUTES: QaRouteEntry[] = [
  {
    path: "/admin",
    surface: "HUB",
    landmark: /What would you like to update/i,
    auth: "aal2",
    roles: ["hq_content_admin", "super_admin"],
    keyControls: ["Programs", "Help & Tutorial", "Menu"],
    viewports: ["390", "1280"],
    mutationRisk: "NAVIGATION",
    workflows: ["tutorial", "public-navigation"],
    a11yScan: true,
    visualEligible: true,
  },
  {
    path: "/admin/website/home",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "PUBLIC_WRITE",
    workflows: ["media-lifecycle"],
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/admin/website/about",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "PUBLIC_WRITE",
    workflows: ["media-lifecycle"],
    a11yScan: false,
    visualEligible: false,
  },
  {
    path: "/admin/website",
    surface: "HUB",
    landmark: /Website pages|Homepage|About KCMI/i,
    auth: "aal2",
    mutationRisk: "NAVIGATION",
    a11yScan: false,
    visualEligible: false,
    notes: "REAL_PRODUCT index — links to website section editors",
  },
  {
    path: "/admin/website/faqs",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "PUBLIC_WRITE",
    a11yScan: false,
    visualEligible: false,
    notes: "REAL_PRODUCT Hub editor",
  },
  {
    path: "/admin/website/global",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "PUBLIC_WRITE",
    a11yScan: false,
    visualEligible: false,
    notes: "REAL_PRODUCT Hub editor",
  },
  {
    path: "/admin/website/sermons",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "PUBLIC_WRITE",
    a11yScan: false,
    visualEligible: false,
    notes: "REAL_PRODUCT Hub editor — sermons page wording",
  },
  {
    path: "/admin/website/services",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "PUBLIC_WRITE",
    a11yScan: false,
    visualEligible: false,
    notes: "REAL_PRODUCT Hub editor",
  },
  {
    path: "/admin/programs",
    surface: "HUB",
    landmark: /program/i,
    auth: "aal2",
    keyControls: ["New program"],
    mutationRisk: "NAVIGATION",
    workflows: ["program-lifecycle"],
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/admin/programs/new",
    surface: "HUB",
    landmark: /New program|About this program/i,
    auth: "aal2",
    keyControls: ["Next step", "Previous step", "Save as a draft"],
    mutationRisk: "DRAFT_WRITE",
    workflows: ["program-lifecycle"],
    a11yScan: true,
    visualEligible: true,
  },
  {
    path: `/admin/programs/${STAGING_QA_PROGRAM_ID}`,
    surface: "HUB",
    landmark: /STAGING QA|DRAFT|When is it|Review/i,
    auth: "aal2",
    keyControls: ["Save draft changes", "program-review-when"],
    mutationRisk: "DRAFT_WRITE",
    workflows: ["program-lifecycle"],
    a11yScan: true,
    visualEligible: true,
    notes: "Known staging QA draft fixture — only safe hosted DRAFT_WRITE target",
  },
  {
    path: "/admin/programs/fixture-published-safety",
    surface: "QA_ONLY",
    auth: "aal2",
    mutationRisk: "SAFE",
    workflows: ["program-lifecycle"],
    a11yScan: false,
    visualEligible: true,
    notes: "QA_ONLY — Requires KCMI_ALLOW_QA_FIXTURES=1",
  },
  {
    path: "/admin/media",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "DRAFT_WRITE",
    workflows: ["media-lifecycle"],
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/admin/branches",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "NAVIGATION",
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/admin/branches/[id]",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "PUBLIC_WRITE",
    workflows: ["media-lifecycle"],
    a11yScan: false,
    visualEligible: false,
    notes:
      "REAL_PRODUCT — exercise representative Headquarters branch via list → detail",
  },
  {
    path: "/admin/livestream",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "PUBLIC_WRITE",
    workflows: ["livestream"],
    a11yScan: true,
    visualEligible: false,
  },
  {
    path: "/admin/sermons",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "NAVIGATION",
    a11yScan: false,
    visualEligible: false,
  },
  {
    path: "/admin/sermons/new",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "DRAFT_WRITE",
    a11yScan: false,
    visualEligible: false,
    notes: "REAL_PRODUCT — safe create form load without final write",
  },
  {
    path: "/admin/sermons/[id]",
    surface: "HUB",
    auth: "aal2",
    mutationRisk: "DRAFT_WRITE",
    a11yScan: false,
    visualEligible: false,
    notes:
      "REAL_PRODUCT — exercise via list → first sermon when present; else NOT_RUN with reason",
  },
];

export const QA_ONLY_ROUTES: QaRouteEntry[] = [
  {
    path: "/qa/d17-public",
    surface: "QA_ONLY",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
  },
  {
    path: "/qa/hub-preview",
    surface: "QA_ONLY",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
  },
  {
    path: "/qa/layout-stress",
    surface: "QA_ONLY",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
  },
];

/** Dynamic public stubs / future surfaces — classified, not treated as missing. */
export const FUTURE_STUB_ROUTES: QaRouteEntry[] = [
  {
    path: "/events/[slug]",
    surface: "PUBLIC",
    auth: "none",
    mutationRisk: "SAFE",
    a11yScan: false,
    visualEligible: false,
    notes: "FUTURE_STUB — representative unpublished/404 behavior only",
  },
];

export const ALL_MANIFEST_ROUTES: QaRouteEntry[] = [
  ...PUBLIC_ROUTES,
  ...AUTH_ROUTES,
  ...HUB_ROUTES,
  ...QA_ONLY_ROUTES,
  ...FUTURE_STUB_ROUTES,
];

export const QA_STATES: QaStateEntry[] = [
  { id: "spotlight-absent", surface: "PUBLIC", description: "Homepage without spotlight", route: "/" },
  { id: "spotlight-present", surface: "PUBLIC", description: "Homepage with spotlight when fixture present", route: "/" },
  { id: "takeover-open", surface: "PUBLIC", description: "Spotlight takeover dialog open", route: "/" },
  { id: "takeover-dismissed", surface: "PUBLIC", description: "Spotlight takeover dismissed", route: "/" },
  { id: "livestream-live-fixture", surface: "PUBLIC", description: "Public livestream live (fixture-dependent)", route: "/livestream" },
  { id: "livestream-not-live", surface: "PUBLIC", description: "Public livestream idle", route: "/livestream" },
  { id: "sermon-exists", surface: "PUBLIC", description: "Sermons listing with content", route: "/sermons" },
  { id: "sermon-fallback", surface: "PUBLIC", description: "Homepage watch/listen fallback", route: "/" },
  { id: "featured-program-exists", surface: "PUBLIC", description: "Featured program on home", route: "/" },
  { id: "no-featured-program", surface: "PUBLIC", description: "No featured program", route: "/" },
  { id: "branch-media", surface: "PUBLIC", description: "Branch detail with media", route: "/locations/headquarters" },
  { id: "branch-no-media", surface: "PUBLIC", description: "Branch without media (fixture-dependent)", route: "/locations/headquarters" },
  { id: "branch-service-times", surface: "PUBLIC", description: "Branch service times present", route: "/locations/headquarters" },
  { id: "branch-missing-time", surface: "PUBLIC", description: "Branch missing time (fixture-dependent)", route: "/locations/headquarters" },
  { id: "mobile-nav-closed", surface: "PUBLIC", description: "Public mobile nav closed", route: "/" },
  { id: "mobile-nav-open", surface: "PUBLIC", description: "Public mobile nav open", route: "/" },
  { id: "locations-query", surface: "PUBLIC", description: "Locations finder with query", route: "/locations", workflows: ["location-finder"] },
  { id: "locations-country-filter", surface: "PUBLIC", description: "Locations country filter", route: "/locations", workflows: ["location-finder"] },
  { id: "program-draft-staging-qa", surface: "HUB", description: "STAGING QA multi-day draft", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}`, fixture: STAGING_QA_PROGRAM_ID, workflows: ["program-lifecycle"] },
  { id: "program-published-safety-fixture", surface: "QA_ONLY", description: "Synthetic published Change→Preview→Make live lock", route: "/admin/programs/fixture-published-safety", workflows: ["program-lifecycle"] },
  { id: "program-create", surface: "HUB", description: "Program create wizard", route: "/admin/programs/new", workflows: ["program-lifecycle"] },
  { id: "program-edit", surface: "HUB", description: "Existing program edit wizard", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}`, workflows: ["program-lifecycle"] },
  { id: "program-one-day", surface: "HUB", description: "One-day schedule semantics", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}`, workflows: ["program-lifecycle"] },
  { id: "program-multi-day", surface: "HUB", description: "Multi-day schedule", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}`, workflows: ["program-lifecycle"] },
  { id: "program-two-sessions-one-day", surface: "HUB", description: "Two sessions same day", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}`, workflows: ["program-lifecycle"] },
  { id: "visitor-action-registration", surface: "HUB", description: "Visitor action Registration", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}` },
  { id: "visitor-action-youtube", surface: "HUB", description: "Visitor action YouTube", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}` },
  { id: "visitor-action-facebook", surface: "HUB", description: "Visitor action Facebook", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}` },
  { id: "visitor-action-other", surface: "HUB", description: "Visitor action Other URL", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}` },
  { id: "visitor-action-none", surface: "HUB", description: "No visitor link", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}` },
  { id: "current-image", surface: "HUB", description: "Current photo placement", route: "/admin/website/home", workflows: ["media-lifecycle"] },
  { id: "proposed-image", surface: "HUB", description: "Proposed photo before Make Live", route: "/admin/website/home", workflows: ["media-lifecycle"] },
  { id: "media-chooser", surface: "HUB", description: "Media chooser open", route: "/admin/website/home", workflows: ["media-lifecycle"] },
  { id: "phone-preview", surface: "HUB", description: "Full preview Phone mode", route: "/admin/website/home" },
  { id: "desktop-preview", surface: "HUB", description: "Full preview Desktop mode", route: "/admin/website/home" },
  { id: "dashboard-tour", surface: "HUB", description: "Dashboard orientation tour", route: "/admin", workflows: ["tutorial"] },
  { id: "homepage-tour", surface: "HUB", description: "Homepage contextual tour", route: "/admin/website/home", workflows: ["tutorial"] },
  { id: "program-tour", surface: "HUB", description: "Program contextual tour", route: `/admin/programs/${STAGING_QA_PROGRAM_ID}`, workflows: ["tutorial"] },
  { id: "livestream-tour", surface: "HUB", description: "Livestream contextual tour", route: "/admin/livestream", workflows: ["tutorial"] },
  { id: "hub-mobile-menu-open", surface: "HUB", description: "Mobile Hub Menu open", route: "/admin" },
  { id: "livestream-off", surface: "HUB", description: "Hub livestream not live", route: "/admin/livestream", workflows: ["livestream"] },
  { id: "livestream-preview", surface: "HUB", description: "Hub livestream check/preview", route: "/admin/livestream", workflows: ["livestream"] },
];

/** Explicit classification for former source-only paths. */
export const SOURCE_ROUTE_CLASSIFICATION = {
  "/admin/branches/[id]": "REAL_PRODUCT",
  "/admin/programs/fixture-published-safety": "QA_ONLY",
  "/admin/sermons/[id]": "REAL_PRODUCT",
  "/admin/sermons/new": "REAL_PRODUCT",
  "/admin/website": "REAL_PRODUCT",
  "/admin/website/faqs": "REAL_PRODUCT",
  "/admin/website/global": "REAL_PRODUCT",
  "/admin/website/sermons": "REAL_PRODUCT",
  "/admin/website/services": "REAL_PRODUCT",
  "/events/[slug]": "FUTURE_STUB",
} as const;

export const SOURCE_APP_PATHS = [
  "/",
  "/about",
  "/about/apostle-frank-aikins",
  "/locations",
  "/locations/[slug]",
  "/services",
  "/sermons",
  "/contact",
  "/giving",
  "/livestream",
  "/events",
  "/events/[slug]",
  "/faqs",
  "/privacy",
  "/terms",
  "/mission",
  "/auth/sign-in",
  "/auth/mfa",
  "/admin",
  "/admin/website",
  "/admin/website/home",
  "/admin/website/about",
  "/admin/website/global",
  "/admin/website/faqs",
  "/admin/website/services",
  "/admin/website/sermons",
  "/admin/programs",
  "/admin/programs/new",
  "/admin/programs/[id]",
  "/admin/programs/[id]/preview",
  "/admin/programs/fixture-published-safety",
  "/admin/media",
  "/admin/branches",
  "/admin/branches/[id]",
  "/admin/sermons",
  "/admin/sermons/new",
  "/admin/sermons/[id]",
  "/admin/livestream",
  "/qa/d17-public",
  "/qa/hub-preview",
  "/qa/layout-stress",
] as const;
